# Generated by Django 5.0.2 on 2024-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfa', '0003_user_email_or_phone_alter_content_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.PNG', null=True, upload_to='profile_pics'),
        ),
    ]
